### ISSUE TITLE
Musescore crashes when trying to play a sound from the sound manager

### ISSUE THREAD

**Issue by thomasheartman** [thilobillerbeck/muse-sounds-manager-nix#1]
Hey!

First off: thanks for bundling the package 😄 I found it in [package request thread](https://github.com/NixOS/nixpkgs/issues/216432#issuecomment-1942809581) and thought I'd give it a go.

My issue is that Musescore appears to crash whenever it tries to play a sound using one of the managed sounds. Playing the default soundfont that's bundled with Musescore works just fine.

Running it from a terminal, I get this error message when it crashes:

```
Fatal (internal) error in ../src/opus_decoder.c, line 108: assertion failed: st->stream_channels == 1 || st->stream_channels == 2
```

My shell then tells me that it's been terminated:

```
fish: Job 1, 'mscore' terminated by signal SIGABRT (Abort)
```

Does that sound familiar to you? I'm really not sure what's going on here. Happy to give more details if you let me know what you need. And of course: if you don't know what's up or don't have the time to help me out, that's perfectly fine too ☺️ 

Thanks again!

**Comment by thomasheartman** [comment]
I did some more research, and this doesn't seem to be exclusive to NixOS. There's a [whole thread over at musescore](https://github.com/musescore/MuseScore/issues/21838) about it crashing on Arch and Manjaro. They're citing the same issue, so I'm going to assume it's on MuseScore's plate. 

That said, if you've got this working on, I'd be keen to hear about how. I've got MuseScore 4.2.1 using the unstable version of NixOS. Maybe it works on stable?

Anyway, I've started tracking the other thread, so I'll close this. Thanks again for your time 😄

**Comment by ShawkMusic** [comment]
I had the exact same error on Arch and got it working again by downgading the `opus` package to version 1.4

Maybe you can figure out a way to do something similar on Nix? (Aren't flakes meant to help with this kinda thing? Still trying to wrap my head around those)
